spring:
  application:
    name: spring-security
  datasource:
    url: jdbc:mysql://localhost:3306/security-check?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    show-sql: true
    format-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

server:
  port: 8080

info:
  app:
    name: "Spring Security Demo"
    description: "Complete study of Spring Security"
    version: "1.0.0"
